version: '3.9'
services:
  adguardhome:
    image: adguard/adguardhome
    ports:
      - '3000:80'
      - '53:53/tcp'
      - '53:53/udp'
      - '853:853/tcp'
      - '853:853/udp'
      - '784:784/udp'
      - '8853:8853/udp'
      - '5443:5443/tcp'
      - '5443:5443/udp'
    volumes:
      - adguardwork:/opt/adguardhome/work
      - adguardconf:/opt/adguardhome/conf
    restart: unless-stopped

volumes:
  adguardwork:
  adguardconf: